### ISSUE TITLE
qiushibaike.py中attr[0]不能用

### ISSUE THREAD

**Issue by wonderffee** [zengqiu/spider#1]
不知道为什么，我运行时得到的attr不是数组，而是属性名，比如attr[0] == "title"要改成attr == "title"才能用，thumb[0][1] == "thumb"我要改成thumb['class'] == "thumb"才能用

我用的是beautifulsoup4-4.3.2，是跟我的BeautifulSoup版本有关系吗？求教

**Comment by zengqiu** [comment]
我的BeautifulSoup版本是3.2.1，高版本不能使用，需要更改代码。
